version: "3.9"

services:
  django:
    build: ./backend
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: supersecretkey123
      FRONTEND_URL: http://localhost:3000
      ALLOWED_HOSTS: "*"
      DEBUG: "True"
    restart: always

  nextjs:
    build: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - django
    restart: always
